---
- name: Configure Apache as required by Koha
  copy: src=../files/koha-httpd.conf dest=/etc/httpd/conf.d/koha.conf

- name: Create a user for Koha
  user: name=koha comment="Koha server" group=apache system=true

- name: Make perl find the Koha modules
  file: src=/usr/share/koha/lib/{{ item }} dest=/usr/share/perl5/vendor_perl/{{ item }} state=link force=yes
  with_items:
    - C4
    - Koha
    - OpenILS
    - Koha.pm
  notify: restart apache

- name: Make Koha find the 64 bit Zebra module
  file: src=/usr/lib64/idzebra-2.0 dest=/usr/lib/idzebra-2.0 state=link force=yes
  when: ansible_userspace_bits == 64

- name: Configure services to run Zebra
  copy: src=../files/{{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  with_items:
    - zebraidx
    - zebrasrv
  notify: restart zebraidx

# Credits: http://jensd.be/587/linux/tips-tricks-for-ansible
- name: SELinux, check loaded modules
  shell: semodule -l
  register: selinuxmodules
  always_run: yes
  changed_when: False

- name: SELinux, copy module to allow zebradb socket access
  action: copy src=../files/zebra_custom.pp dest=/tmp/zebra_custom.pp owner=root mode=600
  when: "selinuxmodules.stdout.find('zebra_custom') == -1"

- name: SELinux, install module to allow zebradb socket access
  command: semodule -i /tmp/zebra_custom.pp
  when: "selinuxmodules.stdout.find('zebra_custom') == -1"

- seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

#- name: Add cronjobs for Koha
#  copy: src=../files/koha-cron dest=/etc/cron.d/koha

# Defaults for firewall, SELinux, Zebra and PazPar2 seem to work.
# TODO: Define ServerName in Apache configuration
